### ISSUE TITLE
Stream numbers

### ISSUE THREAD

**Issue by rr-** [fmang/opustags#14]
Man page reads:

>The identifer of a stream is determined from its position in the file. The first Opus stream found will have id 1, the second 2, and so on. Non-Opus streams are not numbered.

>You can select more than one stream with this option by separated id's with commas. For example: --stream 1,3. Ranges are not supported.

...but right now, the handlers receive `streamno` rather than sequential stream identifier. As such, running `./opustags test.ogg --export` results in following:

    [Stream -336916309]
    LANGUAGE=und
    HANDLER_NAME=SoundHandler
    ENCODER=Lavc57.24.102 libopus
    MAJOR_BRAND=isom
    MINOR_VERSION=512
    COMPATIBLE_BRANDS=isomiso2avc1mp41

which is not what the manpage promised.

I don't think maintaining sequential order should be handled by `TagHandlers`, cause it'll need to introduce duplicated code everywhere. I'd like to let `actions.cc` deal with this.

**Comment by fmang** [comment]
Commit 1ff2553 implements that. Remains to decide whether to include unknown (non-Opus) stream when assigning sequence numbers. See the commit's message.

**Comment by rr-** [comment]
Imho it should include unknown streams in the numbering sequences. Consider how the user might use different tools that are aware of such streams - they might fall under the impression that `opustags` doesn't see such streams, or even strips them away on tag writing.

**Comment by fmang** [comment]
You're totally right. That's settled then.
