### ISSUE TITLE
--editor

### ISSUE THREAD

**Issue by rr-** [fmang/opustags#2]
Blocked by parsers that #1 is going to introduce, user should be able to edit the tags in --import fashion via `$EDITOR`.

Not sure how to spawn processes nicely in portable fashion, I'm probably going to use the dreaded `system()` call since that's what seems most  to be the most portable.

**Comment by rr-** [comment]
@fmang: is this alright if we fire `$EDITOR` once for each stream? IMO yes, totally

**Comment by fmang** [comment]
I think it's better to call `list_tags` once to get all the tags, spawn the editor, then seek back to the beginning of the file and call `edit_tags`.

`list_tags` reads only the first few pages, so it shouldn't have a big impact on performance, while improving the user interface for multi-stream files.

**Comment by rr-** [comment]
Doesn't seeking back blow up everything you coded thus far regarding stream handlers?

**Comment by fmang** [comment]
The `Decoder` object you pass to `list_tags` will break as soon as you rewind the file, but you just have to create a new `Decoder`.

**Comment by fmang** [comment]
Implemented in e4ca6ca6ef3e85d32887c70aa4418882a4aa5e23.
