### ISSUE TITLE
getline is called without the corresponding #include <stdio.h>

### ISSUE THREAD

**Issue by yurivict** [fmang/opustags#31]
Here: https://github.com/fmang/opustags/blob/master/src/cli.cc#L187

Failure log: http://beefy9.nyi.freebsd.org/data/113amd64-default/547769/logs/opustags-1.3.0.log
OS: FreeBSD 11.3

**Comment by fmang** [comment]
Thanks for reporting! I’d gladly accept a merge request for this, otherwise I’ll take care of it next week.

**Comment by yurivict** [comment]
But please note that ```src/cli.cc``` still doesn't have ```#include <stdio.h>``` that the ```getline(3)``` manpage calls for.
