### ISSUE TITLE
need to explicitely include <optional>

### ISSUE THREAD

**Issue by omar-polo** [fmang/opustags#33]
Hi,

I am not able to build opustags as it fails during compilation because of

```
In file included from /home/op/build/opustags/src/cli.cc:10:
/home/op/build/opustags/src/opustags.h:390:7: error: no template named
      'optional' in namespace 'std'
        std::optional<std::string> path_out;
        ~~~~~^
...
```

I am not proficient in C++, so I'm not able to properly fix this, but if I add an explicit include in opustags, it builds fine.

```diff
Index: src/opustags.h
--- src/opustags.h.orig
+++ src/opustags.h
@@ -31,6 +31,7 @@
 #include <functional>
 #include <list>
 #include <memory>
+#include <optional>
 #include <string>
 #include <vector>
 ```

I'm using clang 10.0.1 on OpenBSD.  Also, FYI to build here it also needs the `target_link_libraries` to iconv.

I've just fixed a bunch of tags on various ogg files, thanks for developing this :)

**Comment by fmang** [comment]
Thanks for the report! I’ve create a pull request that you can test for the iconv issue.
