### ISSUE TITLE
Please support `VISUAL` environment variable for `--edit`

### ISSUE THREAD

**Issue by rrthomas** [fmang/opustags#35]
See https://unix.stackexchange.com/questions/4859/visual-vs-editor-what-s-the-difference

For example, I have `EDITOR=emacsclient` so that it works when I have a tty login, and I have `VISUAL=emacsclient -c`, i.e. "open in a new window", for when I have an X (or X-tunnelling) login.

**Comment by rrthomas** [comment]
(OK, I admit: I found `--edit` to be more useful than I thought! :) )

**Comment by fmang** [comment]
I knew about VISUAL but honestly thought this was a relic. If some people use it, I’ll implement it without hesitation.

**Comment by rrthomas** [comment]
I believe it's newer than EDITOR!

-- 
https://rrt.sc3d.org
