### ISSUE TITLE
Please preserve the timestamp after `--edit` if no changes are made

### ISSUE THREAD

**Issue by rrthomas** [fmang/opustags#36]
It seems to me logical that if I close the editor without changing anything, the timestamp should be preserved.

**Comment by rrthomas** [comment]
Fair enough!

-- 
https://rrt.sc3d.org

**Comment by fmang** [comment]
Do you mean you’re convinced by my Git mimicry, or that we should forbid non-interactive options with --edit? If you don’t see a use case for combining -s and --edit, I don’t either, so the latter option is quite good.

**Comment by rrthomas** [comment]
Actually, originally I was convinced by your "git mimicry", but I thought about it some more and I agree that mixing interactive and non-interactive editing is likely to lead to confusion. Also, I'm thinking that the most common way to edit tags is in a GUI, and when you do that, you normally have to click Save or some other positive action to change the tags. (I use EasyTag.)
