### ISSUE TITLE
Broken funtionality under musl

### ISSUE THREAD

**Issue by 0xJes** [fmang/opustags#46]
Some code in this program uses gnu libc specific `//TRANSLIT` suffix which is not supported in musl libc, I discovered this by [trying to package opustags for Void Linux](https://www.reddit.com/r/voidlinux/comments/ki2kf3/creating_a_package_with_an_issue_on_musl/).

[musl](https://musl.libc.org/) is an alternative libc used in Linux distributions like Alpine, Adélie and Void.

[See iconv section in this wiki page](https://wiki.musl-libc.org/functional-differences-from-glibc.html)

I don't know how hard it would be to support musl libc, do you think it can be done?

**Comment by fmang** [comment]
Thanks for the report. I’ll look into that.

I never liked //TRANSLIT in the first place so maybe I’ll drop it and
introduce --raw for users with encoding issues instead.

Have you confirmed opustags works file if you remove //TRANSLIT?

**Comment by 0xJes** [comment]
I changed line 174 on src/cli.cc to: 
```cpp
static ot::encoding_converter from_utf8("UTF-8", "");
```
Now seems to work fine, the program prints tags from files and I can edit tags with `--edit`
