### ISSUE TITLE
Incorrect CMake version requirement

### ISSUE THREAD

**Issue by adromanov** [fmang/opustags#48]
README.md states that CMake version >= 3.9 is required.
I have CMake 3.10 and I can't build the project since `FindIconv` module is missing
```
$ cmake --version
cmake version 3.10.2
$ cmake ..
CMake Error at CMakeLists.txt:22 (include):
  include could not find load file:

    FindIconv
```
According to [CMake documentation](https://cmake.org/cmake/help/latest/module/FindIconv.html) `FindIconv` module was added in 3.11

**Comment by fmang** [comment]
Fixed by ea00b8fd8089ffce58e9826c05aae4da90af3ab5. Thanks for the report!
