### ISSUE TITLE
error: Reading header packets spanning multiple pages are not yet supported. Please file an issue to make your wish known.

### ISSUE THREAD

**Issue by RobertKosten** [fmang/opustags#49]
Know all ye folks by these presents that I do wish so ;) Trying to remove chapter-marks from some podcasts that trip up my player and I assume they are stored as tags (as is commonly done with mp3 files). "Test" files can be found at http://raumzeit-podcast.de/feed/opus, e.g. https://raumzeit-podcast.de/podlove/file/2984/s/feed/c/opus/rz092-weltraumschrott-bekaempfung.opus

**Comment by fmang** [comment]
Oh no!

This is something that requires a bit of thinking, so I need to save up some spare energy. 

I gotta say thanks for the sample though. RFCs are all fun but who knows what actually works in the real world.

**Comment by RobertKosten** [comment]
:-D

Take your time, I am just glad there is a small cli tool available to mangle opus tags (I'm quite baffled opus-tools doesn't include an "opuscomment"). I love implementing RFCs "from spec" myself, but: the more popular, the weirder the "mistaken" implementations get *rolls eyes* :-P

**Comment by zvezdochiot** [comment]
Hi @RobertKosten .

See also [opuscomment](https://github.com/Sound-Linux-More/opuscomment)

**Comment by fmang** [comment]
The feature is ready for the next release.
