### ISSUE TITLE
Let TagHandler know when all streams have been processed

### ISSUE THREAD

**Issue by rr-** [fmang/opustags#6]
There are a few ways to accomplish this:

1. Create an event `ITagsHandler::start_of_file(const int stream_count)`
2. Create an event `ITagsHandler::end_of_file()`
3. Both?

In any case, I'd like to avoid introducing any kind of state to `ITagsHandler` and let `StreamTagsHandler` deal with state as a part of its implementation.

**Comment by fmang** [comment]
Option 2 has been ready for a while, it's called end_of_stre

**Comment by rr-** [comment]
In that case, my proposition would be `end_of_file` or `end_of_streams`. Could you change the name?

**Comment by fmang** [comment]
Done. I added `ITagsHandler::start_of_stream` too so that the lister is aware of the unknown streams.
