### ISSUE TITLE
Open fd to source file prevents inplace rename on SMB

### ISSUE THREAD

**Issue by eduarrrd** [fmang/opustags#62]
When using `--in-place` rename, https://github.com/fmang/opustags/blob/49bb94841ef6e468ba6dfcade5321c6b814edb3f/src/system.cc#L87 it fails on SMB mounts because `final_name` resolves to the input file which is not yet closed. The syscall returns an EACCES instead. I confirmed this in strace as well.

I'm not quite sure how much of this is WAI on the FS side but this is 100% reproducible on my end. Closing the source file before the rename solves this issue.

**Comment by fmang** [comment]
Thank you for the report! I’ve opened #63. Could you please confirm that it does solve your issue?
