### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iconoclasthero** [fmang/opustags#66]
When starting with an opus file one wants to use opustags on, there's no information known about the existing tags.  Using a utility like ffprobe or mediainfo give some information, but largely they do not show what the actual tags for which the values are being changed. 
(I.e., TITLE is a tag with a value of "The Title Book" for _The Title Book_.) 

~~At present, I do not know whether opustags is case sensitive for the tag, but I suspect it is.~~ It does not appear that opustags treats the tags as case sensitive for the purposes of matching existing tags, but it does _preserve_  the case when it saves. 

If I really want the raw tags _as opustags itself sees as the raw tags_, the only option I can find is e.g.,  `opustags -e title_book.opus -o title_book-e.opus` .  This shows what the tags are, caps state, etc.:

encoder=Lavc60.6.101 libopus
ALBUMARTIST=An Artist
artist=An Artist
album=The Title Book
title=001 - The Title Book
TRACKNUMBER=001
genre=Audiobook
TLEN=169906
DESCRIPTION=Read by A. Dude
date=2011

The ability to list the tags **_that opustags actually sees_**, as opposed to the format that e.g., mediainfo puts them in would be most helpful in this regard.

So what I would like is a -l that will pull the information that goes to nano but **L**ist it to STDOUT instead:

$ opustags -l title_book.opus
encoder=Lavc60.6.101 libopus
ALBUMARTIST=An Artist
artist=An Artist
album=The Title Book
title=001 - The Title Book
TRACKNUMBER=001
genre=Audiobook
TLEN=169906
DESCRIPTION=Read by A. Dude
date=2011

$opustags -s ALBUMARTIST="Artist, An" -i title_book.opus

**Comment by fmang** [comment]
The command you are looking for is `opustags title_book.opus`.

opustags comes with a man page that you can access with `man opustags`. You can also open it right from the git repository with `man ./opustags.1`. The case-insensitiveness of --delete is documented, along with usage examples at the end.

**Comment by iconoclasthero** [comment]
Is this not the syntax above?  If it is not, please let me know what is wrong as it does not work (nor does adding -i in front of the file name.
```
$ opustags Wilmington\'s\ Lie\ --\ Part\ 01.opus .
error: Exactly one input file must be specified.
```

I'm of the opinion that it is best to put stuff where people look.  If people didn't look in opustags -h, then you wouldn't have it.  It's there because it's a quick reference.  Man files are often impenetrable to casual users (e.g., just try reading man bash and understand how compgen works if you don't already understand how bash works).  Case in point:  When I worked for Merck, KGaA, we would get tech service calls about the molarity of common concentrated inorganic acids (HCl, H2SO4, etc.).  This happened a lot.  I said to the product manager, "Hey Judy, put that on the label, it'll cut down on the calls to TS."  She did and it did.  When you put the information where people look for it, they find it.
