### ISSUE TITLE
Settle on #include style

### ISSUE THREAD

**Issue by rr-** [fmang/opustags#7]
`tests/actions_tests.cc` vs `src/main.cc`

**Comment by fmang** [comment]
Here's my preferred order for header inclusion, roughly based on relevance:
* headers defining the interface we implement (if applicable),
* headers part of our project,
* library headers,
* system headers.

This order helps ensure headers include their own dependencies.

I usually separate these groups with a blank line, and sort them using the default alphetical-ish order.

I'll leave this issue open to discussion for a week, then will fix the existing files. It's hardly an issue in my opinion though, but I don't wanna fall into the “style doesn't matter” category.
